### ISSUE TITLE
SCIM mongodb performance issue

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#191] opened 2021-08-18 17:43 UTC
Hello guys, I noticed performance issue in case of a lot of users assigned to specific group (500 for example). It takes 8 min to add a  new user to this group calling PATCH

This piece of code makes an update foreach user inside the group:
![image](https://user-images.githubusercontent.com/10979448/129946087-2f59d6c7-6ef8-41e7-a82b-4ccd635e8a59.png)

So delete update many many times. I have a question on that, I saw that now there is a collection representationAttributes, is this collection just temporary? Because in my case now is empty.

Thanks.

**Comment by simpleidserver** [comment] 2021-08-18 20:59
Hello,

I made the following changes in the branch "release/2.0.0" :
1. The collection "SCIMRepresentationAttribute" has been removed.
2. The class  "RepresentationReferenceSync" has been updated in order to return only the modified entities (not the 500 users).
3. The SCIMRepresentationCommandRepository/Update operation is using "ReplaceOneAsync" instruction.

I'm going to make some investigation next week to check if the performance can be improved. 
Anyway, with the modifications the performance is better :)

**Comment by gabrielemilan** [comment] 2021-08-19 06:54
Hello, thank you very much.

Meanwhile, I have a question, I saw that the lifetime of SCIMRepresentationCommandRepository is singleton. Could there be problems with _session added last time? I mean conflict problem or something similar. Is it safe? Or is better to set lifetime of 
SCIMRepresentationCommandRepository as scoped?

Thanks.

**Comment by simpleidserver** [comment] 2021-08-19 12:09
Hello,

You're right, the configuration present in the "MongoDB" project is not ideal and can be a risk.
In the current implementation, there is no issue with the "_session" because it is created by each HTTP REQUEST via the instruction : "`using (var transaction = await _scimRepresentationCommandRepository.StartTransaction())`".
The class "ServiceCollectionExtensions" has been updated in the branch "release/2.0.0".

Kind regards,

SimpleIdServer

**Comment by gabrielemilan** [comment] 2021-08-19 13:41
Ok :-)

Now the performance is better.

I noticed that this query takes a lot of time in case of multiple ids:

![image](https://user-images.githubusercontent.com/10979448/130078830-8a76ed23-8c3a-4662-8362-0a725556264f.png)

I don't know if can help.

Thanks

**Comment by francesco-scullino** [comment] 2021-08-19 15:19
> 
> 
> Ok :-)
> 
> Now the performance is better.
> 
> I noticed that this query takes a lot of time in case of multiple ids:
> 
> ![image](https://user-images.githubusercontent.com/10979448/130078830-8a76ed23-8c3a-4662-8362-0a725556264f.png)
> 
> I don't know if can help.
> 
> Thanks

Moreover the foreach below run a query for each user already present in a group. Every time to get the same User schema document. I suppose this is the reason why the response time of a patch call, to add a user in a group, is proportional to the number of user already inside the group.

![image](https://user-images.githubusercontent.com/1720798/130094485-24038257-3d67-45b0-969d-b44ff594a495.png)

**Comment by gabrielemilan** [comment] 2021-08-19 15:41
Indeed the issue could be on the foreach:

![image](https://user-images.githubusercontent.com/10979448/130099063-57007775-af27-442c-aa1b-157ba791cc6c.png)

**Comment by simpleidserver** [comment] 2021-08-19 15:44
Hello,

Thank you for your feedback ! I already noticed this issue, i'm going to fix it next week.

Kind regards,

Simpleidserver

**Comment by simpleidserver** [comment] 2021-08-24 12:15
Hello,

First of all, thank you about your feedback :)
We made some the following changes in the branch "release/2.0.0" in order to fix the performance issue :
* Return the representations concerned by the changes. The *FindSCIMRepresentationByIds* function returns only the representations impacted by the HTTP request.
* Update the FindSCIMRepresentationByIds in order to improve the performance.

**Comment by francesco-scullino** [comment] 2021-09-08 12:54
Hello @simpleidserver  team
as usual, thanks for your reactivity.

I tested the new version and the performance increased a lot. :)
You can compare the following diagram with the previous one:

![image](https://user-images.githubusercontent.com/1720798/132512309-517d05c0-83c1-400f-91a7-c51ac53222d0.png)

Anyway I is there an ascending trend of response time based on the number of users already in the group. I cannot evaluate the reason this time.

Thanks for your great job
Francesco

**Comment by simpleidserver** [comment] 2021-09-08 13:57
Hello,

We discovered a performance issue in the `RepresentationReferenceSync` class. 
When a group is patched with a new user, the following instruction takes more than 806ms to execute `newIds = newIds.Where(i => !oldIds.Contains(i)).ToList();`.
This instruction has been replaced by `newIds = newIds.Except(oldIds).ToList();` and it takes 10ms to execute.

The changes have been committed in the branch "release/2.0.1" can-you please check if the performance are better ?

https://github.com/simpleidserver/SimpleIdServer/commit/0b5bedeb636f0dc9d8e446bbff348c3f1a13d096

Kind regards,

SimpleIdServer

**Comment by francesco-scullino** [comment] 2021-09-08 16:11
Hi,
you are right, the performace increased again, but the ascending trend is already in place:

![image](https://user-images.githubusercontent.com/1720798/132545409-d134ac1d-7665-4e8e-9050-e663a63b3597.png)

I suppose some logic optimization it needs to be more scalable.

Kind regards,
Francesco

**Comment by simpleidserver** [comment] 2021-09-09 14:27
This problem occurs when the MongoDb document (Group) becomes larger. In fact it takes more time to load and update the document. Until we find a solution to fix this problem, the recommendation consists to execute a PATCH operation on the User to assign to a group.
We execute 300 PATCH operations on a user & we didn't notice performance problem :

![PatchUser](https://user-images.githubusercontent.com/10213388/132702936-908295a4-c0a4-4949-ad15-4085057f4ce9.png)

Patch operation: 

```
{
 "schemas": [ "urn:ietf:params:scim:api:messages:2.0:PatchOp"],
 "Operations": [ 
 	{ "op": "add", "path": "groups", "value": [ { "value" : "b3c7c7c7-f192-41ca-bbeb-66b294085278" } ] }
 ]
}
```

**Comment by francesco-scullino** [comment] 2021-09-21 07:59
Hello,
is there any update on this? Unfortunately execute a PATCH operation on the User to assign to a group is not feasible in our use case.

Thank you very much
Francesco

**Comment by simpleidserver** [comment] 2021-09-21 13:54
Hello,

I didn't find a valid solution to improve the performance of the PATCH operation.
This operation is made of several blocks & some of them can have an impact on the performance :

* **Get group** : the group becomes larger when there are more users assigned to this group. Therefore the operation will take more time to execute.

| Nb Users | Execution time |
| -------- | -------------- |
| 1        | 2ms            |
| 300      | 17ms           |

* **ApplyPatch** : this operation applies changes on the group like :  AddUser, UpdateTitle etc... The existing members must be fetched to check if there is no duplicate. When this list becomes larger then it will take more time to execute.

| Nb Users | Execution time |
| -------- | -------------- |
| 1        | 2ms            |
| 300      | 14ms           |

* **Sync** : Assign the group to the user.
* **SaveChanges** : When data is larger then it will take more time to execute.

| Nb Users | Execution time |
| -------- | -------------- |
| 1        | 1ms            |
| 300      | 17ms           |

I made some modifications in the "Sync" operation in order to improve the performance. https://github.com/simpleidserver/SimpleIdServer/commit/ffeb31b5133daac8c060bda91b8664675b4f57f0

| Nb Users | Execution time |
| -------- | -------------- |
| 300      | 40ms (before)  |
| 300      | 14ms (after)   |

Even if the operation will take more time to execute, the performance is acceptable. 
As you can see in the graph below, **it takes less than 150ms for each operation to assign a user**.

![SimpleIdServer Scim Benchmark ScimBenchmark-AddUserToGroup-Job-EEXIWH-cummean](https://user-images.githubusercontent.com/10213388/134183463-c6766f18-493b-4ebe-bb4f-b559a8f014c5.png)

Can-you please fetch the latest changes of the branch "release/2.0.1" & identify where you have performance problem in the class "PatchRepresentationCommandHandler.
I used the project "SimpleIdServer.Scim.Benchmark" to add one group & assign 300 users & add "Stopwatch" to calculate the execution time of each block.

**Comment by simpleidserver** [comment] 2021-10-15 13:07
Hello, 

In fact, I'm a bit surprised about the performance problem you have. 
The previous benchmark image, I sent, has been generated by using [this algorithm](https://github.com/simpleidserver/SimpleIdServer/tree/master/src/Scim/SimpleIdServer.Scim.Benchmark).

Can-you please check if this algorithm is correctly reproducing your scenario, if it's the case, can-you please execute the benchmark "SimpleIdServer.Scim.Benchmark.csproj", compress the directory "BenchmarkDotNet.Artifacts" into a zip file and send it ?

Kind regards,

SimpleIdServer

**Closed** 2023-03-03 21:00 UTC
Labels: bug
