### ISSUE TITLE
[SCIM] query a group id on the users controller and vice versa returns the resource

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#422] opened 2023-02-21 14:19 UTC
Hello,

I noticed that in 2.0.25, I can do the following:

- Assume we have a group with `group-id` and a user with `user-id`.
- I can query `groups/user-id` and `users/group-id` and it returns data.

Kind regards
Dan

**Comment by simpleidserver** [comment] 2023-02-21 15:52
The issue is fixed in the branch `release/2.1.0`.

KR,

SID

**Comment by simpleidserver** [comment] 2023-02-28 21:22
Hello,

The Nuget Package version 3.0.0 is available, it contains the modifications made on the branch `release\2.1.0`.

KR,

SID

**Closed** 2023-09-06 19:33 UTC
Labels: bug
