### ISSUE TITLE
SimpleIdServer.Scim.Swashbuckle error in runtime

### ISSUE THREAD

**Issue by boris-meerovich-sp** [simpleidserver/SimpleIdServer#54] opened 2020-11-10 08:51 UTC
In SimpleIdServer.Scim.Swashbuckle\SCIMSchemaGenerator.cs, GenerateReferencedSchema() method, row 176
schema.Properties.Remove(schema.Properties.First(_ => .Key == "Attributes"));
I got exception: System.InvalidOperationException: 'Sequence contains no matching element'
for schema.Properties.First( => _.Key == "Attributes") row.
Any of my schemas contain Attributes in Properties.

I mentioned it already in https://github.com/simpleidserver/SimpleIdServer/issues/53#issuecomment-711802678

Occurring in version 1.1.8

My solution is to call FirstOrDefault instead of First.

**Comment by simpleidserver** [comment] 2020-11-10 20:33
The issue is fixed in the *master*, First operation has been replaced by FirstOrDefault.

**Comment by boris-meerovich-sp** [comment] 2020-11-11 08:07
Thanks!!!
I will work on the master for a while...

**Closed** 2020-11-11 08:07 UTC
