### ISSUE TITLE
Missing "resourceType" in "meta" attribute in the ServiceProviderConfig 

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#331] opened 2022-09-16 19:49 UTC
According to [SCIM Core Schema: Common Attributes](https://www.rfc-editor.org/rfc/rfc7643#section-3.1) there is should be _resourceType_ in **meta** attribute.

**Comment by simpleidserver** [comment] 2022-09-19 12:24
The issue is fixed in the branch `master`.

**Closed** 2022-10-14 10:41 UTC
