### ISSUE TITLE
Email verification error

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#672] opened 2023-12-29 07:54 UTC
Click on the email in the bottom right corner of the 5001 page, and the email can be successfully sent. However, when I fill in the received verification code in the input box and click the 'update button', an error message appears:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f909c9a6-6269-4170-87fb-171480276035)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/24e232c5-5c0c-426f-98d3-43e66c031c4d)

**Comment by simpleidserver** [comment] 2024-01-01 20:36
The issue is fixed in the `master` branch :)

**Closed** 2024-01-02 01:26 UTC
Labels: bug
