### ISSUE TITLE
Updating fields with parent for the same value returns 200 code but 204 returns when updating fields without parent

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#358] opened 2022-12-07 14:25 UTC
**1.** Send a PATCH request with updating a field with parent (i.e. “name.givenName“) with the same value.

http://{url}/users/{id}

```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "name.givenName",
            "value": "fname"
        }
    ]
}
```
→ **it returns 200 OK** status code with full user details (not changed)

**2.** Send a PATCH request with updating a field without parent (i.e. “userName“) with the same value.

http://{url}/users/204200

```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "userName",
            "value": "test@email.com"
        }
    ]
}
```

→ **it returns 204** status code

Behavior differs for fields with and without parent when there is trying to save the same value as the user has at that moment.
Probably there should be one type of code for any field.

The difference is in SimpleIdServer.Scim.Domain.SCIMRepresentationExtensions.ApplyPatches method. Inside this method Merge and ReplaceComplexMultiValuedAttribute methods are called. For one of them attribute filtration contains comparison by FullPath (FullPath == fullPath) and Value (na.IsSimilar(a, true)), but for another one there is comparison by FullPath only.

Possible fix:
![image](https://user-images.githubusercontent.com/93668324/206203480-97727709-4bd3-4d14-b6f6-a01209d57eae.png)

**Comment by simpleidserver** [comment] 2022-12-07 20:10
Hello,

The issue is fixed in the branch `release/v2.0.22`.

KR,

SID

**Closed** 2022-12-15 09:05 UTC
Labels: bug
