### ISSUE TITLE
PATCH: missing validation for required field in requests

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#420] opened 2023-02-21 08:01 UTC
There is **500** Error if no _value_ field in request. Should be **400** as _value_ is required field.

**add** operation:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "name.givenName"
        }
    ]
}
```

**replace** operation:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "name.givenName"
        }
    ]
}
```

According to [RFC-7644: 3.5.2.2  Remove Operation](https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2.2) it should be possible to do remove operation without _value_ field. Now it's 500 error.

Example request body:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "remove",
            "path": "name.givenName"
        }
    ]
}
```

Please notice that it also should work for sub-properties in _path_.

**Comment by simpleidserver** [comment] 2023-02-21 15:34
The issue is fixed in the branch `release/2.1.0`.

KR,

SID

**Comment by simpleidserver** [comment] 2023-02-28 21:21
Hello,

The Nuget Package version 3.0.0 is available, it contains the modifications made on the branch `release\2.1.0`.

KR,

SID

**Comment by aliaksiejmaroz** [comment] 2023-03-06 11:46
It works for **string-type** attributes, but it doesn’t work for a **bool** attributes.

**Closed** 2023-03-22 13:18 UTC
