### ISSUE TITLE
ResourceTypes endpoint returns "totalResults" and "itemsPerPage" not equal to number of resources in the body

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#320] opened 2022-09-08 08:22 UTC
GET [https://{{Server}}{{Port}}/ResourceTypes](https://%7B%7Bserver%7D%7D%7B%7Bport%7D%7D/ResourceTypes) returns the next response:
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "totalResults": 2,
    "itemsPerPage": 2,
    "startIndex": 1,
    "Resources": [
        {
            "schemas": [
                "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
            ],
            "id": "User",
            "name": "User",
            "description": "User Schema",
            "endpoint": "/Users",
            "schema": "urn:ietf:params:scim:schemas:core:2.0:User",
            "schemaExtensions": [
                {
                    "schema": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
                    "required": false
                }
            ],
            "meta": {
                "location": "",
                "resourceType": "ResourceType"
            }
        }
    ]
}
```
"totalResults" and "itemsPerPage" attributes equal 2 value but should be equal 1

**Comment by simpleidserver** [comment] 2022-09-08 12:46
Hello,

The issue is fixed in the branch `master` and a pre-release package (version SimpleIdServer.Scim 2.0.17-ci-00346) is already available : https://www.myget.org/feed/advance-ict/package/nuget/SimpleIdServer.Scim

KR,

SID

**Closed** 2022-10-14 10:09 UTC
Labels: bug
