### ISSUE TITLE
[SCIM] Error patch on 4.0.4

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#595] opened 2023-10-05 15:10 UTC
Hello,

I face this error using 4.0.4 version:

`{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations":[ 
            {
            "op":"replace", 
            "path": "active", 
            "value": false
            } 
        ]
}`

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/9e17ac64-5119-4e83-95d8-883c96896abe)

**Comment by simpleidserver** [comment] 2023-10-08 19:13
Hello,

Due to the modifications made in the release "4.0.4" to improve the performance of the SCIM project, there are some unexpected regressions :(

The issue has been fixed in the branch "release/4.0.5" :)

If you notice any other regressions, please don't hesitate to create bug tickets.

Best regards,

SID

**Comment by polybogdan** [comment] 2023-10-09 08:19
Hello,

Testing the 4.0.5 we noticed the following issues:

1. Patch on a mongo database that has a lot of data the patch returns a server error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/86643363-5b96-4706-8b41-9f1b58eddcf7)

2. Fields updated with the patch operations are added also as properties in the name and email objects
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/bf9d2d4b-898a-4780-9ff5-3335aaa8f35d)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/1d575fa7-aaed-4ec6-aeb1-dd4e3e1b9ea5)

Let me know if you prefer creating different bug tickets for the issues above.

Regards

Bogdan

**Comment by simpleidserver** [comment] 2023-10-09 12:22
Hello,

There is no need to create an another ticket, all the bugs can be reported into this ticket.
Both bugs are fixed in the branch `release/4.0.5`.

KR,

SID

**Comment by simpleidserver** [comment] 2023-10-10 20:58
Hello,

I can publish a pre-release next thurdsay (12/10).

KR,

SID

**Comment by simpleidserver** [comment] 2023-10-11 19:53
@polybogdan : The release `4.0.5-rc1` is published !

https://www.nuget.org/packages/SimpleIdServer.Scim/4.0.5-rc1

**Closed** 2024-06-07 14:31 UTC
Labels: bug
