### ISSUE TITLE
[SCIM] Issue on update group

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#34] opened 2020-05-04 11:34 UTC
Hello,

when I try to update the group with put call I noticed that if the group has 2 members, only one has been saved in database.

I think that the problem is caused by this part of code:
![image](https://user-images.githubusercontent.com/10979448/80961660-b32bd480-8e0b-11ea-9348-264c4a015047.png)

As you can see the code delete the attribute by schema id, but can happens that a group has more than one members, that has same schema id.

This is the payload of put call:
{
    "displayName": "test",
    "meta": {
        "resourceType": "Group"
    },
    "members": [
        {
            "value": "dd9d1e55-82de-4454-ad2b-0a558ca12dfe"
        },
        {
            "value": "da1e6331-5e94-4403-b380-5ad15c6c4e28"
        }
    ],
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ]
}

Thanks.

**Comment by simpleidserver** [comment] 2020-05-04 13:32
We are going to make some investigations ASAP.

**Comment by simpleidserver** [comment] 2020-05-04 20:11
The issue is fixed in the branch "release/1.1.3" : https://github.com/simpleidserver/SimpleIdServer/commit/a4a36e4b46630e09460c91a33b2afde3e99b60e9

**Closed** 2020-05-08 13:19 UTC
Labels: bug
