### ISSUE TITLE
The example fails to run

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#751] opened 2024-05-23 07:16 UTC
Hello, excuse me, I configured the client according to [Delegation or Impersonation](https://simpleidserver.com/docs/tutorial/delegation/) , but when I ran your corresponding sample, there was an error in changing the position in "ShopApi" :
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ed0cc090-5bc7-4bc0-bad7-1cecc1c67fe3)

**Comment by qq1176914912** [comment] 2024-05-23 08:44
There is also this demo:[wsfederation](https://simpleidserver.com/docs/tutorial/wsfederation/), I found that you must use the "administrator" account to log in, if you use another account to log in, 5001 will appear this error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/af581d8d-d1f5-400a-92e8-313a15c4c252)

**Comment by simpleidserver** [comment] 2024-05-23 20:10
Both issues are fixed in the `master` branch.

**Comment by qq1176914912** [comment] 2024-05-24 01:48
> Both issues are fixed in the `master` branch.



> Both issues are fixed in the `master` branch.

Thank you for your modification. For  [wsfederation](https://simpleidserver.com/docs/tutorial/wsfederation/), I tested it and found that when 5001 was deployed locally (localhost), I could successfully log in using other accounts. However, when I deployed 5001 to a remote server (accessed through the domain name), I logged in using the account "administrator" normally. But when I use other accounts, the demo will report an error, what is the situation?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/64fb1eb7-5ab8-4780-81a7-70103afeff84)

**Comment by simpleidserver** [comment] 2024-05-24 09:41
Could you make the modifications in your client to show the "PII" and copy the error into the conversation?

For more information, please refer to the official documentation: 

https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.logging.identitymodeleventsource.showpii?view=msal-web-dotnet-latest

**Comment by qq1176914912** [comment] 2024-05-24 09:49
> Could you make the modifications in your client to show the "PII" and copy the error into the conversation?
> 
> For more information, please refer to the official documentation:
> 
> https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.logging.identitymodeleventsource.showpii?view=msal-web-dotnet-latest

Ok, this is I in the project with "IdentityModelEventSource. ShowPII = true;" The result of
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/65b34912-6960-42d7-8c03-dc9974f41f17)

**Comment by qq1176914912** [comment] 2024-05-24 09:59
Is it because I arbitrarily changed the encryption of the user password? I changed the way you previously stored your password (to the database).

**Comment by qq1176914912** [comment] 2024-05-28 01:26
> > Could you make the modifications in your client to show the "PII" and copy the error into the conversation?
> > For more information, please refer to the official documentation:
> > https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.logging.identitymodeleventsource.showpii?view=msal-web-dotnet-latest
> 
> Ok, this is I in the project with "IdentityModelEventSource. ShowPII = true;" The result of ![image](https://private-user-images.githubusercontent.com/79817742/333540136-65b34912-6960-42d7-8c03-dc9974f41f17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NTk3NjYsIm5iZiI6MTcxNjg1OTQ2NiwicGF0aCI6Ii83OTgxNzc0Mi8zMzM1NDAxMzYtNjViMzQ5MTItNjk2MC00MmQ3LThjMDMtZGM5OTc0ZjQxZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAxMjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzA0OWNhYzgxODgyZjZiNzdmZDRhNTViYTkzYWI1NTUxNjVhYzMxMWY1ZTViNGMwNDQ2NTNjZjI2OWJhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U81UF-MjdNqTwsiXcLSF6tuUP14NGDClBnMjBRZmuiY)

Hello, excuse me.
I see your modified version number: "031333 f6fc1d9d1b5bfb43e2a30c86abcbb776df", I was with my old postgresql tested before, when we use the other account can normal login, but the sqlite library for the old version is wrong before, There is no problem if you ask the program to create a new sqlite library, so what do I do with the old sqlite library? Do you want to clear a table?

**Comment by qq1176914912** [comment] 2024-05-31 08:06
> > > Could you make the modifications in your client to show the "PII" and copy the error into the conversation?
> > > For more information, please refer to the official documentation:
> > > https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.logging.identitymodeleventsource.showpii?view=msal-web-dotnet-latest
> > 
> > 
> > Ok, this is I in the project with "IdentityModelEventSource. ShowPII = true;" The result of ![image](https://private-user-images.githubusercontent.com/79817742/333540136-65b34912-6960-42d7-8c03-dc9974f41f17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NTk3NjYsIm5iZiI6MTcxNjg1OTQ2NiwicGF0aCI6Ii83OTgxNzc0Mi8zMzM1NDAxMzYtNjViMzQ5MTItNjk2MC00MmQ3LThjMDMtZGM5OTc0ZjQxZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAxMjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzA0OWNhYzgxODgyZjZiNzdmZDRhNTViYTkzYWI1NTUxNjVhYzMxMWY1ZTViNGMwNDQ2NTNjZjI2OWJhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U81UF-MjdNqTwsiXcLSF6tuUP14NGDClBnMjBRZmuiY)
> 
> Hello, excuse me. I see your modified version number: "031333" f6fc1d9d1b5bfb43e2a30c86abcbb776df, before I use my old "postgresql" test, when we use the other account can normal login, but the sqlite library for the old version is wrong before, There is no problem if I ask the program to create a new "sqlite" library, so what do I do with the old version of the sqlite library? Do you want to clear a table?

Excuse me, do you have any ideas? I don't want to recreate the library.

**Comment by qq1176914912** [comment] 2024-05-31 08:53
With your latest master project, there was a problem testing [FapiGrantManagement](https://github.com/simpleidserver/SimpleIdServer/tree/f59860cc0c0b210a95241943b13f0292f11c1fc4/samples/FapiGrantManagement):

![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/cf56ec7b-1d61-4495-a15a-5705975e0507)

**Comment by simpleidserver** [comment] 2024-05-31 12:23
Hello,

Regarding the WS-Federation issue:

Can you clean the "SerializedFileKeys" table and try again?

For FAPI Grant-Management:

The issue is fixed in the master branch.

**Comment by qq1176914912** [comment] 2024-06-03 03:12
> Hello,
> 
> Regarding the WS-Federation issue:
> 
> Can you clean the "SerializedFileKeys" table and try again?
> 
> For FAPI Grant-Management:
> 
> The issue is fixed in the master branch.

Regarding the WS-Federation issue:
Thank you for your suggestion that the "SerializedFileKeys" table cannot be cleared. If clearing the table would cause the 5001 program to fail to start, I found that simply deleting the account with this error and adding it again could solve the problem.

And I also found a new problem, using the latest mater project, when using sqlite, when the application automatically creates sqlite libraries, there is an error message:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/bba16c3b-6e11-4a79-bf5d-7d899956d05c)

For FAPI Grant-Management:
Thank you. Problem solved

**Comment by simpleidserver** [comment] 2024-06-03 11:31
An exception was thrown during startup because the migration scripts were not applied before the AutomaticConfigurationProvider class tried to get values from the table. A check has been added in the "KeyValueRepository" and the issue is now fixed.

**Closed** 2024-06-05 09:45 UTC
Labels: bug
