### ISSUE TITLE
Find the problem

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#755] opened 2024-06-12 07:17 UTC
Hello, excuse me, I found a problem when I tested the group in the user. When the current user did not have a group, I assigned a group to the user. After adding successfully, without switching the menu, click the right button twice, and the group in the list will disappear.

https://github.com/simpleidserver/SimpleIdServer/assets/79817742/3143e754-2c0e-4479-9925-da64ea14c1e8

**Comment by simpleidserver** [comment] 2024-06-12 19:19
Hello,

The issue is fixed in the `master` branch

**Closed** 2024-06-13 01:39 UTC
