### ISSUE TITLE
[SCIM] Sorting doesn't work in MongoDB 

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#408] opened 2023-02-09 12:26 UTC
Hi guys,

I notice that the sortBy and sortOrder attribute don't work in Mongo db version.

Regards.

**Comment by simpleidserver** [comment] 2023-02-09 20:33
Hello,

First thank you for your feedback :)
The issue is fixed in the branch `release/v2.0.26`, the sorting feature were missing in the Mongo DB version.

KR,

SID

**Comment by simpleidserver** [comment] 2023-02-09 21:21
A pre-release package is available with the fix 

```
dotnet add package SimpleIdServer.Scim.Persistence.MongoDB --version 2.0.26-ci-00398 --source https://www.myget.org/F/advance-ict/api/v3/index.json
dotnet add package SimpleIdServer.Scim --version 2.0.26-ci-00398 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Closed** 2023-09-06 19:33 UTC
Labels: bug
