### ISSUE TITLE
Server error occurs when trying to get Groups are not presented in the scheme

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#327] opened 2022-09-15 08:29 UTC
**Steps to reproduce:**

Send Get request to https://{{Server}}{{Port}}**/Groups**

**Result:**

500 server error is returned in the response with the body:
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "500",
    "scimType": "internalServerError",
    "detail": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at SimpleIdServer.Scim.Api.BaseApiController.InternalSearch(SearchSCIMResourceParameter searchRequest)"
}
```
**Expected Result:**

404 status code is returned as Groups are not present in the current scheme.
404 status code is currently returned for all other not existing urls (/test, as example)

**Reproducible for other types of requests: Post, Put…**

**Comment by simpleidserver** [comment] 2022-09-15 08:56
Hello,

Good remark :)
The issue is fixed in the `master` branch. If the `ResourceType` doesn't exist in the database then 404 is always returned.

KR,

SID

**Closed** 2022-10-14 10:10 UTC
Labels: bug
