### ISSUE TITLE
[SCIM] Error in bulk insert using version 4.0.5 

### ISSUE THREAD

**Issue by polybogdan** [simpleidserver/SimpleIdServer#679] opened 2024-01-15 09:26 UTC
Hello,

I'm facing an issue when doing the following call to insert an user with entitlements and the SupportTransaction of the MongoSettings is set to true.

```
{
    "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
    "emails": [
        {
            "type": "work",
            "value": "test12@mail.com",
            "primary": true
        }
    ],
    "name": {
        "familyName": "Test familyName",
        "givenName": "Test givenName"
    },
    "displayName": "Test displayName",
    "active": true,
    "userName": "test12@mail.com",
    "entitlements": [
        {
            "value":"421578a6-5cd1-4ef7-bf86-1580f25d28f7"
        }
    ]
}
```

![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/fcc4b042-7498-4c2d-9fdf-87e6d801e7ba)

Exception occurs in the BulkInsert :
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/9a77340a-612d-488f-938d-86e141be86cd)

**Comment by simpleidserver** [comment] 2024-01-15 21:21
The problem has been resolved in the `master` branch. When a transaction was created, it was not passed during the querying process, and as a result, the application was unaware of the entity added during the transaction.

**Comment by simpleidserver** [comment] 2024-01-15 21:22
I made some modifications in the `master` branch to enhance performance during querying. 
There was an issue with the following code:

```
IQueryable<EnrichedRepresentation> representationAttributes = from a in _scimDbContext.SCIMRepresentationLst.AsQueryable()
    join b in _scimDbContext.SCIMRepresentationAttributeLst.AsQueryable() on a.Id equals b.RepresentationId into FlatAttributes
    select new EnrichedRepresentation
    {
        Id = a.Id,
        ExternalId = a.ExternalId,
        Version = a.Version,
        Representation = a,
        FlatAttributes = FlatAttributes
    };
```

The Aggregate executed too many $lookup operations, causing a performance problem. 
To address this issue, the algorithm's order has been changed as follows:
* Filter the representations.
* Sort the representations.
* Paginate the representations.
* Load the attributes of the representations.

Could you please clone the master branch and check if the performance is improved with these changes?

**Comment by LazaroOnline** [comment] 2024-03-25 05:39
if the issue is closed in the project board, shouldn't it be also closed here in "issues"?

**Closed** 2024-06-07 14:30 UTC
Labels: bug
