### ISSUE TITLE
Invalid login redirect?

### ISSUE THREAD

**Issue by jhermsen** [simpleidserver/SimpleIdServer#444] opened 2023-03-03 14:49 UTC
If I try to open for example on the IdServer /consents it redirects to /Account/Login instead of the /Home/Authenticate.
Is this a setting I have to change?

I'm working with the new 3.0 version on docker.

**Comment by simpleidserver** [comment] 2023-03-03 15:41
Hello,

There is an issue in the IdentityServer's configuration.
By default, if you're are not authenticated and you're trying to access to a protected controller (/home/profile), then you'll be redirected to the action /account/login.

Because IdServer can support multiple authentication methods like `email/Authenticate`, `pwd/Authenticate` or `sms/Authenticate`, you must be redirected to the URL `pwd/Authenticate`.

The issue is already fixed in the branch `release\v3.0.2`.

KR,

SID

**Closed** 2023-09-06 19:34 UTC
Labels: bug
