### ISSUE TITLE
[SCIM] PATCH `Add` operation on already exists resource

### ISSUE THREAD

**Issue by ZahiC** [simpleidserver/SimpleIdServer#245] opened 2022-03-24 09:10 UTC
If an already exists member is re-added an 409 error response with `duplicate reference` error is returned. According to the [`Add Operation` RFC](https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2.1):

<img width="578" alt="image" src="https://user-images.githubusercontent.com/15949736/159881621-5245138f-fb8d-4628-8c7c-456009777178.png">

Input example:
```
{
  schemas: ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
  Operations: [{
    op: "add",
    path:"members",
    value: [{
      value: ...,
      display: ...
    }]
  }]
}
```

**Comment by simpleidserver** [comment] 2022-03-24 14:51
Hello,

Indeed there is an issue. We are working on it.

Kind Regards,

SimpleIdServer

**Comment by simpleidserver** [comment] 2022-03-24 16:15
The issue is fixed in the branch "release/2.0.6".

**Comment by JWMB** [comment] 2022-03-26 08:24
I've tested the 2.0.6 branch, and the added conditional above seemed to be needed - otherwise exceptions will be thrown even for the "duplicate" existence of e.g. the property "members".

Also the response code is still 409 instead of the spec's `a success response SHOULD be returned`. [This thread](https://docs.microsoft.com/en-us/answers/questions/471809/azure-ad-scim-provisioning-repeating-requests-for.html) suggests 204.

(As an asider, Azure ADs group provisioning flow seems strange at times; after adding users to groups successfully, it still retries the PATCH operations. Perhaps it expects a slightly different response to the `GET Groups/Get [id]` request, will look into it next week)

**Comment by simpleidserver** [comment] 2022-03-26 08:56
Hello,

First thank you for your feedback. Indeed, the condition must be updated otherwise unexpected conditions can occurred.
We are going to update the branch "release/2.0.6" to fix this issue.

Kind Regards,

SimpleIdServer

**Comment by simpleidserver** [comment] 2022-03-28 11:26
Some changes have been made in the branch "release/2.0.6":
* Returns "204" instead of 409
* Add "Any" checks

**Closed** 2023-03-03 21:07 UTC
Labels: bug
