### ISSUE TITLE
PATCH: 204 is returned if hierarchical parameter replaced to an empty value

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#418] opened 2023-02-17 11:49 UTC
**Steps to reproduce:** send **PATCH** request with body
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "name",
            "value": ""
        }
    ]
}
```
(_name_ has sub properties like _givenName_ etc) it is response with **_204_** status code.

**Expected result:** it is **_400 Bad Request_** with error message in response body ([Issue](https://github.com/simpleidserver/SimpleIdServer/issues/417) has been created).

**ANOTHER ONE CASE**

Send Patch request for a user with empty Operations list
```

{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": []
}
```
**204** status code has been returned

**Expected result:** **400** status code returned with Error response body ("scimType": "invalidSyntax", "detail" etc) because the list must contain one or more objects (according to [RFC 7644: System for Cross-domain Identity Management: Protocol](https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2)

**Comment by simpleidserver** [comment] 2023-02-21 14:28
The issue is fixed in the branch `release/v2.1.0`.

KR,

SID

**Closed** 2023-03-22 09:47 UTC
Labels: bug
