### ISSUE TITLE
SCIM - /schemas endpoint issue

### ISSUE THREAD

**Issue by PetrutiuPaul** [simpleidserver/SimpleIdServer#242] opened 2022-03-21 11:59 UTC
When returning all the schemas, the mutability property has values like : immutable, readonly, writeonly, etc. In the rfc documentation looks like the props values should be camel case : immutable, readOnly, writeOnly, etc...

**Comment by simpleidserver** [comment] 2022-03-21 14:41
Indeed it's an issue.
We are going to work on it.

Kr,

SimpleIdServer

**Comment by simpleidserver** [comment] 2022-03-22 12:27
The issue is fixed in the branch "release/2.0.6"

**Closed** 2022-03-22 13:20 UTC
Labels: bug
