### ISSUE TITLE
[SCIM] Error on uniqueness check on 3.0.4

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#514] opened 2023-05-26 12:07 UTC
Hello, following the bug #510 , I noticed that in the new version 3.0.4 the check of uniqueness doesn't work at all.

It seems that the problem is on flatten data:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/8f5f1401-df12-4503-b2a9-6029d3061759)

In the document there is no representation and representationId, the code to check the unique field, try to get the representation using representationId, that is always null.

To test the bug you can add two users with same userName.

P.S.: I noticed that now there is this new collection for flat attributes, why not using the flat attributes inside representation document? Why duplicate the data?

Can you please check?

**Comment by simpleidserver** [comment] 2023-05-26 12:34
I m going to take a look to this problem asap.

Kr,

Sid

**Comment by simpleidserver** [comment] 2023-05-26 19:22
Hello,

Due to the changes made on the ticket #416, there is a small regression with the `Add` function.
The issue is fixed in the `master` branch.
We will publish a release candidate, when all the bugs related to SCIM are fixed.

KR,

SID

**Comment by simpleidserver** [comment] 2023-05-31 18:31
The release `3.0.5-rc1` is published. It contains the following features : https://github.com/simpleidserver/SimpleIdServer/projects/56

**Closed** 2024-06-07 14:36 UTC
Labels: bug
