### ISSUE TITLE
meta attributes are not present for resources in /Schemas

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#339] opened 2022-10-25 11:09 UTC
**Steps to reproduce:**

Send **Get** https://{{Server}}{{Port}}**/Schemas** request

Take a look into properties for one of the resources from the response see response attached

**Result:** 
there are no meta attributes

**Expected Result:**
”meta” attribute with “resourceType“ and “location“ sub-attributes (at least) should be present for each resource in the list

As an example:
```json
 "meta" : {
      "resourceType" : "Schema",
      "location" : "/v2/Schemas/urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
 }
```

**Documentation:**

Example of Resource Schema Representation from rfc https://www.rfc-editor.org/rfc/rfc7643#section-8.7

Information about common attributes https://www.rfc-editor.org/rfc/rfc7643#section-3.1

Schemas endpoint is not in the list of exceptions for common attributes:

![image](https://user-images.githubusercontent.com/93668324/197757731-917701b8-f182-4ede-9e56-5d52fb00bea0.png)

**Comment by simpleidserver** [comment] 2022-10-26 09:04
Hello,

The issue is fixed in the branch `master` :)

KR,

SID

**Comment by andreidabryian** [comment] 2022-10-26 12:46
Thanks! When release 2.0.20 is going to be?

**Comment by simpleidserver** [comment] 2022-10-29 19:36
The version `2.0.20` is released :)

**Closed** 2022-11-14 07:47 UTC
Labels: bug
