### ISSUE TITLE
[SCIM] Performance issues version 4.0.5

### ISSUE THREAD

**Issue by polybogdan** [simpleidserver/SimpleIdServer#682] opened 2024-01-15 13:08 UTC
Hello,

I'm facing some performance issues when doing GET groups and each group has around 100 members and the number of total groups are around 1000.

Bellow some scenarios:

1. When passing the sorting parameters the query results are received in 1 minute and 30 seconds
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/9bdc6cc8-2b82-4370-af0c-3b39c00b12a5)

2. Without the sorting parameters the  query results are received in 30 seconds that is still too much
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/0ed4d085-e7b5-4d76-96ff-0c69eb2df432)

3. I saw that there is an option to pass the excludedAttributes where we set the "members" and the query results are 20 seconds that is still too much
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/7b2d9432-4c15-4364-bb25-6743d1b8d5f1)

Is there something that can be improved on the library side ?

Regards 

Bogdan

**Comment by simpleidserver** [comment] 2024-01-15 21:22
I made some modifications in the `master` branch to enhance performance during querying. 
There was an issue with the following code:

```
IQueryable<EnrichedRepresentation> representationAttributes = from a in _scimDbContext.SCIMRepresentationLst.AsQueryable()
    join b in _scimDbContext.SCIMRepresentationAttributeLst.AsQueryable() on a.Id equals b.RepresentationId into FlatAttributes
    select new EnrichedRepresentation
    {
        Id = a.Id,
        ExternalId = a.ExternalId,
        Version = a.Version,
        Representation = a,
        FlatAttributes = FlatAttributes
    };
```

The Aggregate executed too many $lookup operations, causing a performance problem. 
To address this issue, the algorithm's order has been changed as follows:
* Filter the representations.
* Sort the representations.
* Paginate the representations.
* Load the attributes of the representations.

Could you please clone the master branch and check if the performance is improved with these changes?

**Comment by polybogdan** [comment] 2024-01-16 09:27
Hello,

Thanks for the quick fix.
I'm testing the version and will get back to you with the feeback.

Regards

**Comment by polybogdan** [comment] 2024-01-16 11:11
Hello again,

Summing up the test results for each of the initial described scenario.
1. When passing the sorting parameters the query results were received in 1 minute and 30 seconds
 Now the query results are received in around 20 seconds ( big improvement ) 
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/fcf3dad0-8a34-4016-bd03-de60c2502d21)

2. Without the sorting parameters the query results were received in 30 seconds
 The tests result for this one are a bit random. Something e the query results are received in around 30 seconds ( like before ) and sometimes they are received in 12 seconds
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/ddba463c-2be4-47a4-b382-bb4be0b5d0ec)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/7fe11669-81eb-4eaa-a40c-64d32a0dbcfc)

3. Passing the excludedAttributes where we set the "members" and the query results were 20 seconds 
 The tests result for this one are a bit random. Something e the query results are received in around 30 seconds ( slower then before ) and sometimes they are received in 10 seconds ( a bit better ) 
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/a72dd993-a6bf-4815-ad43-2fec30bb50aa)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/ae23e355-369d-452e-b090-9e51effa6aab)


Additionally i noticed that the get Users has some issues:
1. /Users?sortBy=name.familyName&sortOrder=ascending does not sort 
2. /Users?filter=groups[display eq "GroupName"] is not working and previously it was 

Let me know if there is something else that can be done

Regards

Bogdan

**Comment by simpleidserver** [comment] 2024-01-16 15:16
"I made some modifications in the master branch to improve performance with MongoDB. The issues you mentioned have also been fixed. Could you please fetch the latest changes and try again?

**Comment by simpleidserver** [comment] 2024-01-17 13:16
The following issues have been fixed in the`master` branch :
* /Users?filter=groups[display eq "GroupName"]
* /Users?filter=id eq "66afdcc9-93b3-446d-a875-8f9f07b5e281"

Regarding the HTTP request /Users?sortBy=name.familyName&sortOrder=ascending&filter=name[givenName co "Bodgan"], I attempted to reproduce the problem on my local machine without success.

Could you please check in the `representations` MongoDB collection if the representation that should be returned by the HTTP request contains a resource type equal to 'Users'?

Additionally, could you check if the HTTP request /Users?sortBy=name.familyName&sortOrder=ascending&filter=name[givenName co "Bodgan"] returns any results?

**Comment by polybogdan** [comment] 2024-01-17 14:40
Going to check asap the latest changes.

For the last one 
 /Users?sortBy=name.familyName&sortOrder=ascending&filter=name[givenName co "Bodgan"]

In fact is acting strangely
/Users?sortOrder=ascending&sortBy=**name.familyName**&filter=name[**givenName** co "Bogdan"] 
returns totalResults 2 ( that is correct and in the Resources array only one item
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/78799e1c-c9a3-4d52-b808-4c550f3b7376)


changing the sortBy to "name.givenName" it doesnt
/Users?sortOrder=ascending&sortBy=name.givenName&filter=name[givenName co "Bogdan"]
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/c5f57306-ab09-4549-9333-ec36ae7aaa41)

event the following doesnt work
/Users?sortOrder=ascending&sortBy=name.familyName&filter=emails[value eq "bogdan.poliec@mail.com"]
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/8a442c27-e99f-4465-99a1-2f33a929851a)

The response body reflect the result seen in postman
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/f7f41e02-f942-44d5-83c5-69d28af8fe9d)

By this : Could you please check in the representations MongoDB collection if the representation that should be returned by the HTTP request contains a resource type equal to 'Users'?
You were expecting this check ?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/73d25d7c-226a-4d35-9aaa-fccf6c81f130)

**Comment by polybogdan** [comment] 2024-01-17 15:04
After last pull from master :
- /Users?filter=groups[display eq "GroupName"] is ok
- /Users?filter=id eq "d153b387-b832-4b32-b78e-5c0ebe91ead3" results in server error 
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/9d563626-9bdc-4ea3-b41c-03c7c443d181)
- GET Groups are again slow
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/7a6db72f-210e-4b42-a50a-945fcf617768)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/baa96cde-1ec9-432d-9bf3-b6e8a04f8507)

-Similar to the GET users issue has ( paginng and filter parameters do not return results )
/Groups?startIndex=101&count=100&filter=displayName eq "EURO 2024-FO_Broadcaster" 
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/f5174af4-df79-4f6d-8ddc-9a81503cb003)

**Comment by simpleidserver** [comment] 2024-01-17 15:14
I believe I have identified the issue with the sortBy operation. 
Could you please pull the latest changes from the master branch and try again?

About the "internalServerError", do-you have the stack trace?

**Comment by polybogdan** [comment] 2024-01-22 16:10
Hello, 

Sorry for the late reply.

- /Users?filter=id eq "d153b387-b832-4b32-b78e-5c0ebe91ead3" - filter by id is ok now
- /Groups?sortBy=displayName&sortOrder=ascending&startIndex=101&count=100&filter=displayName co "UCL" does not return the results
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/3ec06095-826a-4d05-8dbd-a71f4137c942)
i noticed that the issue is related somehow to the sorting inside FindSCIMRepresentations
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/c2eb3a93-b570-4b4c-bdd3-411b5e15b3d9)
commenting out the row 126 the results are returned ( not sorted tho )
- Related to the performance issues of the GET Groups on a local database with around 4000 users, 700 groups, 900 entitlements and 
each group with around 100 members 
some members with around 80 groups 
entitlements with 200 members
the response is generally between 3 and 5 seconds 

yet pointing to the mongo db of any other environment the performances are very poor.
I debugged the FindSCIMRepresentations and most of the time spent is the actual query to the database.

at this point i dont know if other performance improvements could be made on the query, besides what you already did, but what i would ask if you can provide some recommended indexes to be applied to the mongo db to speed it up.

**Comment by simpleidserver** [comment] 2024-01-22 19:25
Indexes are automatically created by the SCIM server during its startup. Could you please check if the following indexes are created in the SCIMRepresentationAttribute collection?

* RepresentationId_1_SchemaAttributeId_1_ValueString_1
* RepresentationId_1

Code : https://github.com/simpleidserver/SimpleIdServer/blob/997aad167073c19462b5dd48218dd15b41a30408/src/Scim/SimpleIdServer.Scim.Persistence.MongoDB/Extensions/MongoDbClientExtensions.cs#L55

Regarding the sorting issue, I tested it on my local machine, and everything is working fine. I observed that you set the startIndex to 101 in the request. 
In this case, it is normal for the request to be empty because only 90 results are returned.

**Comment by polybogdan** [comment] 2024-01-23 07:41
Hello,

Regarding the sorting issue, you are right the startIndex was the problem, sorry about that.
I checked the indexes and they are all defined.

At this point i would kindly ask you to release the latest improvements and if possible the fix done for the SupportTransaction flag related to the issue [[SCIM] Error in bulk insert using version 4.0.5](https://github.com/simpleidserver/SimpleIdServer/issues/679)

**Comment by simpleidserver** [comment] 2024-01-24 19:36
Hello,

The Nuget package `4.0.7-rc1` https://www.nuget.org/packages/SimpleIdServer.Scim is available :)

KR,

SID

**Closed** 2024-06-07 14:35 UTC
Labels: bug
