### ISSUE TITLE
SCIMSchemaGenerator does not work with EF SCIM Store

### ISSUE THREAD

**Issue by aidas-simkus** [simpleidserver/SimpleIdServer#243] opened 2022-03-23 07:42 UTC
When SCIM server is set up to use EF as a persistence store and at the same time it is configured to use Swagger, the below exception is being thrown.

`Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.ApiDescriptions.IDocumentProvider Lifetime: Singleton ImplementationType: Microsoft.Extensions.ApiDescriptions.DocumentProvider': Cannot consume scoped service 'SimpleIdServer.Scim.Persistence.EF.SCIMDbContext' from singleton 'Microsoft.Extensions.ApiDescriptions.IDocumentProvider'.)`

Commenting out `services.AddSCIMSwagger()` in `Startup.cs` fixes the issue and one can launch Swagger, but then it misses some input model definitions (e.g. a model for POST /Users).

Is there something that can be done about this issue?

**Comment by simpleidserver** [comment] 2022-03-23 12:24
Hello,

Oups... We didn't pay attention. The issue is fixed in the branch "release/2.0.6".

Kind regards,

SimpleIdServer

**Closed** 2023-03-03 21:09 UTC
Labels: bug
