### ISSUE TITLE
Get a resource by Id and attributes in query parameters

### ISSUE THREAD

**Issue by AmirHosseinKarimi1997** [simpleidserver/SimpleIdServer#370] opened 2022-12-28 13:02 UTC
Do you support Get API by Id and attributes in query parameters?

The main problem is that we have some requests like this from the azure user provisioning service:
https://test.com/api/v1/scim/Groups/{id}?excludedAttributes=members

but I think there is no way to handle this attributes with `SimpleIdServer.Scim.Api.BaseApiController `.
There is no Get method that accepts `Get(string id, [FromQuery] SCIMResourceAttributes requestAttributes)`  to handle this kind of request.

Based on [RFC for attributes]( https://www.rfc-editor.org/rfc/rfc7644#section-3.4.2.5):
_The following attributes control which attributes SHALL be returned with a returned resource.  SCIM clients MAY use one of these two OPTIONAL parameters, which MUST be supported by SCIM service providers._

Is there any way to handle this behavior?

**Comment by simpleidserver** [comment] 2022-12-29 21:05
Hello,

Indeed this feature is missing from SimpleIdServer.Scim package.
We are going to implement it for the next release.

KR,

SID

**Comment by simpleidserver** [comment] 2022-12-30 08:48
The issue is fixed in the `master` branch and a pre-release package is  available : 

```
 dotnet add package SimpleIdServer.Scim --version 2.0.23-ci-00378 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

KR,

SID

**Comment by AmirHosseinKarimi1997** [comment] 2022-12-30 08:50
Thank you for your quick response and fix. Actually, I wanted to contribute and suggest to you that I can implement this on your repository and review it with you, but it was faster than I thought :).
Just a quick question, When do you want to release this feature?

**Comment by simpleidserver** [comment] 2022-12-30 08:53
This feature will be released next week, once the ticket #343 is fully tested :)

**Comment by AmirHosseinKarimi1997** [comment] 2022-12-30 09:15
Just one comment: I checked the changes and you exclude the data after this line:
`var representation = await _scimRepresentationQueryRepository.FindSCIMRepresentationById(id, _resourceType);`
which means I need to fetch all the data and after that, you are excluding some of them. Currently one of the main problems in our usage, is, for example, we have a request to get one group with Id and also with (`ExcludedAttributes=members`). we have some groups which have lots of users (50k members), so we need to fetch them all and after that, you are excluding the users from the result.
Is there any way to pass these attributes to this function `_scimRepresentationQueryRepository.FindSCIMRepresentationById(id, _resourceType);`.
I know it might be a breaking change, but with this implementation in the commit, our problem won't be solved.
[I commented on the code as well.](https://github.com/simpleidserver/SimpleIdServer/commit/f63d1cf0b92bd5f9d21ddb28bdac62aadcb248be#r94590241)

**Comment by simpleidserver** [comment] 2022-12-30 10:06
Good remark :).
I made some modifications to pass those information into the repository. Only needed attributes are returned by the SQL statement. The same logic is used by the search operation.
Pre-release package is available here:

```
dotnet add package SimpleIdServer.Scim --version 2.0.23-ci-00379 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Comment by AmirHosseinKarimi1997** [comment] 2022-12-30 10:28
Again, thank you for your quick response and fix :).
It will help us to solve the problem.
Thanks.

**Comment by AmirHosseinKarimi1997** [comment] 2023-01-18 10:36
I upgraded to the new version and everything looks good.

**Closed** 2023-03-03 21:08 UTC
Labels: enhancement
